const fs = require("fs"); 
let content = fs.readFileSync("admin.js", "utf8"); 

content = content.replace(/const JSONBIN_ID[\s\S]*?const PUT_URL = `https:\/\/api\.jsonbin\.io\/v3\/b\/\$\{JSONBIN_ID\}`;/, "const GET_URL = `/api/gallery`;\nconst PUT_URL = `/api/gallery`;"); 

content = content.replace(/\/\/ ─── Settings: ImgBB API Key[\s\S]*?\/\/ ─── 1\. Login/g, "// ─── Settings ────────────────────────────────\nfunction toggleSettings() {\n  const body = document.getElementById(\"settings-body\");\n  const arrow = document.getElementById(\"settings-arrow\");\n  body.classList.toggle(\"hidden\");\n  arrow.classList.toggle(\"open\");\n}\n\nfunction loadSavedKey() {}\n\nfunction updateKeyStatus() {}\n\ndocument.getElementById(\"save-key-btn\").onclick = () => {\n  const keyMsg = document.getElementById(\"key-msg\");\n  keyMsg.textContent = \"✅ Updated! Uploads now use local server.\";\n  keyMsg.style.color = \"#4ade80\";\n  setTimeout(() => { keyMsg.textContent = \"\"; }, 3000);\n};\n\n// ─── 1. Login"); 

content = content.replace(/\/\/ ─── 2\. Load Data[\s\S]*?const res = await fetch\(GET_URL[\s\S]*?\}\);/, "// ─── 2. Load Data from local server ──────────────────────────────\nasync function loadData() {\n  saveMsg.textContent = \"Loading gallery data...\";\n  try {\n    const res = await fetch(GET_URL);");

content = content.replace(/\/\/ ─── 4\. Image Upload[\s\S]*?\/\/ ─── 5\. Add YouTube Video/, `// ─── 4. Image Upload (Gallery → Local Server) ───────────\ndocument.getElementById("image-upload").onchange = async (e) => {\n  const files = e.target.files;\n  if (!files || files.length === 0) return;\n\n  const service = galleryData.find((s) => s.slug === currentSlug);\n  if (!service) return;\n\n  if (!service.images) service.images = [];\n  const progressBar = document.getElementById("upload-progress");\n  const progressFill = document.getElementById("progress-fill");\n  const uploadBox = document.querySelector(".upload-box");\n  uploadBox.classList.add("uploading");\n  progressBar.classList.remove("hidden");\n\n  const total = files.length;\n  let uploaded = 0;\n  let failed = 0;\n  uploadMsg.textContent = \`Uploading 0/\${total}...\`;\n  uploadMsg.style.color = "#60a5fa";\n\n  for (const file of files) {\n    try {\n      const formData = new FormData();\n      formData.append("image", file);\n\n      const res = await fetch(\`/api/upload\`, {\n        method: "POST",\n        body: formData,\n      });\n\n      const json = await res.json();\n      if (json.success) {\n        service.images.push(json.data.url);\n        uploaded++;\n      } else {\n        failed++;\n        const errMsg = json.error ? json.error.message : JSON.stringify(json);\n        console.error("Upload error:", errMsg);\n        uploadMsg.textContent = \`❌ Error: \${errMsg}\`;\n        uploadMsg.style.color = "#f87171";\n      }\n    } catch (err) {\n      failed++;\n      console.error("Upload error:", err);\n      uploadMsg.textContent = \`❌ Network error: \${err.message}\`;\n      uploadMsg.style.color = "#f87171";\n    }\n\n    const pct = Math.round(((uploaded + failed) / total) * 100);\n    progressFill.style.width = pct + "%";\n    if (failed === 0)\n      uploadMsg.textContent = \`Uploading \${uploaded + failed}/\${total}...\`;\n  }\n\n  uploadBox.classList.remove("uploading");\n  progressFill.style.width = "100%";\n  if (failed === 0) {\n    uploadMsg.textContent = \`✅ \${uploaded} image\${uploaded > 1 ? "s" : ""} uploaded! Don't forget to Save.\`;\n    uploadMsg.style.color = "#4ade80";\n  } else if (uploaded > 0) {\n    uploadMsg.textContent = \`⚠️ \${uploaded} uploaded, \${failed} failed.\`;\n    uploadMsg.style.color = "#fbbf24";\n  }\n\n  setTimeout(() => {\n    progressBar.classList.add("hidden");\n    progressFill.style.width = "0%";\n  }, 2000);\n\n  renderMedia();\n  e.target.value = "";\n};\n\n// ─── 5. Add YouTube Video`);

content = content.replace(/\/\/ ─── 6\. Save to JSONBin[\s\S]*?body: JSON\.stringify\(galleryData\),\n    \}\);/, "// ─── 6. Save to local server ─────────────────────────────────────\ndocument.getElementById(\"save-btn\").onclick = async () => {\n  saveMsg.textContent = \"💾 Saving changes to server...\";\n  saveMsg.style.color = \"#60a5fa\";\n  try {\n    await fetch(PUT_URL, {\n      method: \"PUT\",\n      headers: {\n        \"Content-Type\": \"application/json\",\n      },\n      body: JSON.stringify(galleryData),\n    });");

fs.writeFileSync("admin.js", content);
